name: Robot Framework CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Robot Framework tests
        uses: joonvena/robotframework-docker-action@v1.0
        with:
          robot_tests_dir: tests
          robot_reports_dir: reports

      - name: Upload Robot Framework reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: robot-reports
          path: reports
